@startuml
title Partner User Input Request Single

(*) --> "Login"
--> "Create Single Request"

    if (Request Status) then (approved)
        -> [approved] "Request Process"
    else
        -> [reject] "Request Cancel"
    else
        -> [revise] "Edit Request"
        -> Submit
        -> Request Status
    endif
' if "Do redirect?" then
'  ->[yes] "redirect request"
'  --> ==BEFORE_DESTROY===
' else
'  if "Do Forward?" then
'   -left->[yes] "Forward request"
'   --> ==BEFORE_DESTROY===
'  else
'   -right->[no] "Render page template"
'   --> ==BEFORE_DESTROY===
'  endif
' endif

--> "Page.onDestroy()"
-->(*)

@enduml