@startuml
left to right direction
skinparam packageStyle rectangle

actor user_partner
user_partner -- (Create Request Inject)
user_partner -- (View Request Inject List)
user_partner -- (View Filtered Request Inject List)
user_partner -- (Edit Request Inject | Need Approval)
user_partner -- (Download Report Inject List)
user_partner -- (Download Report Request Inject Result)

actor user_admin
user_admin -- (View Request Inject List)
user_admin -- (View Filtered Request Inject List)
user_admin -- (Giving Approval, Reject and Edit)
user_admin -- (Download Report Inject List)
user_admin -- (Download Report Request Inject Result)

@enduml